#docker-compose 의 버전
version: '3'

#실행할 서비서들을 정이
# - database-mysql
# - database-adminer
services:
  database-mysql:
    #커스텀한 container 의 이름을 설정
    #사용자가 설정한 템플릿을 이미지라고 한다면 이 이미지를 실행한 상태를 컨테이너라고 한다. 자바로 치면 클래스를 이미지라고 한다면 인스턴스는 컨테이너 같은 관계이다.
    container_name: database-mysql
    image: mysql/mysql-server:8.0

    #이미지가 사용할 환경변수
    environment:
      MYSQL_DATABASE: wada
      MYSQL_USER: shs2810
      MYSQL_PASSWORD: shs2810
      MYSQL_ROOT_PASSWORD: shs2810
      MYSQL_HOST: localhost
      TZ: Asia/Seoul

    volumes:
      - ./mysql-init.d:/docker-entrypoint-initdb.d

    #호스트에서 접속할 외부 포트:도커 내부의 실제 포트
    ports:
      - '13306:3306'

    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'

#  database-adminer:
#    container_name: database-adminer
#    image: adminer:latest
#    ports:
#      - "18080:8080"
#    environment:
#      - ADMINER_DEFAULT_SERVER=database-mysql
#      - ADMINER_DESIGN=hydra
#      - ADMINER_PLUGINS=tables-filter tinymce